apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv 
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0f005ee01fd482a6a