apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv 
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  persistentVolumeReclaimPolicy: Retain  # optional but recommended
  storageClassName: manual               # must match PVC
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-05d8a95c91dd4b1c1 # ✅ your EBS volume ID