apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc 
  
spec:
  storageClassName: "ebs-sc" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic-pod 
  labels:
    purpose: "ebs-dynamic-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic-pvc
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - name: persistent-storage
        mountPath: /usr/share/nginx/html

---
kind: Service
apiVersion: v1
metadata:
  name: ebs-dynamic-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "ebs-dynamic-demo"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # conatiner port
    nodePort: 30007