apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: "ebs-dynamic-sc"
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-dynamic-dep
  labels:
    project: expense
    component: api 
    environmet: prod  
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      component: api 
      environmet: prod
      purpose: "ebs-dynamic-demo"
  template:
    metadata:
      name: ebs-dynamic-pod
      labels:
        project: expense
        component: api 
        environmet: prod
          
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1a
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-dynamic-pvc  
      containers:
      - name: ebs-dynamic-pod
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html


---
kind: Service
apiVersion: v1
metadata:
  name: ebs-dynamic-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "ebs-dynamic-demo"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # conatiner port
    nodePort: 30007 