apiVersion: v1
kind: PersistentVolume 
metadata:
  name: efs-static-pv 
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 18Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0626b2bf740dc56be