apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-sc
spec:
  storageClassName: "efs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-dynamic-sc
  labels:
    environmet: prod
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      environmet: prod
      project: expense
  template:
    metadata:
      name: pod-dep
      labels:
        environmet: prod
        project: expense
    spec:
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-dynamic-sc
      containers: 
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html

---


kind: Service
apiVersion: v1
metadata:
  name: efs-dynamic-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    environmet: prod
    project: expense
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # conatiner port
    nodePort: 30007 