apiVersion: v1
kind: Pod
metadata:
 name: multi-container
#  namespace: expense-dev

spec:
  containers:
  - name: nginx1
    image: nginx

  - name: nginx2
    image: almalinux:9
    command: ["sleep", "2000"]



# multiple containers are useful in few applications like shipping logs through sidecars (fig in notebook)

# ELK stands for:

# ✅ Elasticsearch — Search and analytics engine (for storing and searching logs).
# ✅ Logstash — Data processing pipeline (for collecting, transforming, and sending data).
# ✅ Kibana — Visualization and dashboard tool (for analyzing and visualizing data).

# Together, ELK is a powerful stack used for log management, monitoring, and troubleshooting in DevOps environments. 🚀