# annotations are used to store external information like URL , Image from where your taken 

kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    