apiVersion: v1
kind: Service
metadata: 
  name: clusterip-service
spec: 
  selector:
    name: naveenrajoli
    environment: prod
    project: expense
    component: backend
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    name: naveenrajoli
    environment: prod
    project: expense
    component: backend
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx
    