apiVersion: v1
kind: NodePort
metadata:
  name: node-port-svc

spec:
  selector:
    purpose: to-access-nginx
    ports: inside-pod-open-port-number-80
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000

---

apiVersion: v1
kind: Pod

metadata:
  name: node-port-pod
  labels:
    created_by: naveen-rajoli
    environment: dev
    purpose: to-access-nginx
    ports: inside-pod-open-port-number-80

spec:
  containers:
  - name: nginx
    image: nginx

