apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset 
  labels:  # these labels are replicaset labels
    created_by: naveenrajoli
    environment: dev
    purpose: to-run-desired-pods    
spec:
  replicas: 3
  selector:
    matchLabels: # replicaset use these labels to find the pods for creating desired number of replicas
      environment: dev
      purpose: to-run-desired-pods
  template:
    metadata:
      name: replica-pod
      labels:
        environment: dev
        purpose: to-run-desired-pods 
        service: replica-pod-service # this labels are used to attach to a service
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: replica-svc

spec:
  type: NodePort
  selector:
    service: replica-pod-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000