apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment 
  labels: 
    created_by: naveenrajoli
    SNOW: CHG00065784
    project: expense
    component: frontend-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      component: frontend-nginx
  template:
    metadata:
      labels:
        project: expense
        component: frontend-nginx
        service: port-80-running
    spec:
      containers:
      # - name: nginx
      #   image: nginx:1.14.2
      - name: apache-container
        image: httpd
        ports:
        - containerPort: 80
   
---

apiVersion: v1
kind: Service
metadata:
  name: lb-svc-deployment
spec:
  type: LoadBalancer
  selector:
    service: port-80-running
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 32555